### ISSUE TITLE
Further explanation of the curve types

### ISSUE THREAD

**Issue by fmhall** [essential-contributions/ERC-7521#88]
Great work on this, I'm having a ton of fun playing around with it.

What is the `COUNT` curve and evaluation types? I don't see them in the comments or blog posts anywhere.

The `AssetBasedIntentCurve.sol` file would greatly benefit from more explanatory comments IMO!

Here is the context:

I'm trying to construct an intent with two segments:
1.  Records the ETH balance of the user's account, and releases a set amount of ETH.
2.  Requires 1 wei more ETH than the account had in the first segment.

I think the basic mechanism would be something like this:
```solidity
uint256 ethReleaseAmount = user.balance;
int256[] memory ethRelCurveParams =
            AssetBasedIntentCurveBuilder.constantCurve(int256(uint256(ethReleaseAmount)));
int256[] memory ethReqCurveParams =
            AssetBasedIntentCurveBuilder.constantCurve(int256(uint256(ethReleaseAmount))+1);
UserIntent memory intent = _intent();
intent = intent.addSegment(_segment("").releaseETH(ethReleaseCurveParams));
intent = intent.addSegment(_segment("").requireETH(ethRequireCurveParams, true));
return intent;
```

And the solver intent would be something like:

```solidity
UserIntent memory solverIntent = _solverIntent(
            _myMethodToReturnMoreEth(
                ethReleaseAmount, address(_publicAddressSolver), address(_account)
            ),
            "",
            "",
            1
        );
```

Am I on the right track?

Thanks in advance.

**Comment by pixelcircuits** [comment]
Sorry for the delay. I didn't see your issue until now. 

You're on the right track! However, you need to change the requirement to 
```
int256[] memory ethReqCurveParams =
            AssetBasedIntentCurveBuilder.constantCurve(1); //1wei
```
because the balance recording in the first segment currently happens before any assets are released. However, there is currently issue #72 which aims to change it so balances are recorded after any specified releases or actions for better simplicity and gas efficiency.

`COUNT` is just a placeholder so we know the upper bound of what's allowed. You'll notice in the `validate` function for curves it does checks like `require(curveType(curve) < CurveType.COUNT, "invalid curve type");`
